### ISSUE TITLE
Encoding of "unsafe" characters

### ISSUE THREAD

**Issue by sirpicklesiv** [daverix/urlforwarder#1]
When the characters ":" and "/" are within the replaced text, they are encoded into their HTML strings "%3A" and "%2F".
For example, "https://www.google.com/" becomes "https%3A%2F%2Fwww.google.com%2F".
This may be the proper behavior for strings to be used in a query, however when this occurs for URLs to be used with the site "web.archive.org", it is unrecognizable. The URL "https://web.archive.org/web/*/https%3A%2F%2Fwww.google.com%2F" does not work, and is not recognized because the website expects the full unencoded URL as part of the string.
An option to disable this selectively would be a good solution. Otherwise, this app is very useful and works fine.

**Comment by daverix** [comment]
Hi! That sounds like a simple thing to implement! :)

**Comment by daverix** [comment]
Will be released in 0.3.
