### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by pwmarcz** [daverix/urlforwarder#10]
First of all, thanks for the project, this is exactly what I needed! I started using Pinboard and was looking for the best way to use the bookmarklet on my phone.

The only thing I was missing was forwarding the page title, not only URL. I thought it should be pretty simple to add, and it turned out you already did it in the newest version, not yet released.

I was able to build an `.apk` for myself, but maybe you would consider making a release? Forwarding the title is a really valuable feature.

**Comment by pymander** [comment]
I'm just commenting to say that I also would love this feature! When is a new release planned?

**Comment by daverix** [comment]
Just released v0.4! Will come to Google Play and F-droid shortly
