### ISSUE TITLE
version 0.4 keeps crashing

### ISSUE THREAD

**Issue by Maexotic** [daverix/urlforwarder#11]
Model: Samsung SM-G96F (S9+)
Samsung Android 10 (all patches applied)

Since the 0.4 update the app keeps crashing. Doesn't even try to connect to the URL it should forward to.

**Comment by daverix** [comment]
I'll take a look as soon as possible!

**Comment by daverix** [comment]
Can you share a filter where it crashes?

**Comment by daverix** [comment]
@Maexotic Can you try 0.4.2?

**Comment by Maexotic** [comment]
I have written my own tiny little bookmark system.
I just call an endpoint written in django with .../add/url?url=@url&topic=incoming
It happpend for like 10 different URLs I have tried from Google Chrom via "Share".

I have now installed 0.4.2.
Now I get a overlay windows saying:
"no app found matching <configured backend URL with @url not substituted>"

**Comment by daverix** [comment]
Ok, does your url start with http or https? I shouldn't have changed anything in the Intent used to open other apps, but maybe there is a new behavior when targeting later Android versions.

I could also add the whole url to the error message if that would help.

**Comment by Maexotic** [comment]
I have tried it with both http:// and https:// always the same error.

**Comment by hansdez** [comment]
I just wanted to add that I experienced exactly the same problems. First Url forwarder kept crashing. That is no longer the case, and I not too am getting the “No app found matching https://ichangedthisdomainname.nl/link/add?url=@url” error. This is literally for any url that I try to share with Url forwarder, so regardless of https/http. Needless to say: I can share urls to other appas.

I am using:

- Url forwarder 0.4.2
- Android 10 (on a Fairphone 3)
- Firefox Browser 89.1.1

I loved the Url forwarder functionality (am really suffering without this working actually), so am very happy to help testing something or helping in any other way. Thank you for your work on this @daverix.

**Comment by daverix** [comment]
I managed to reproduce this now but leaving "replaceable subject" empty. Could you try adding something like "@subject" in that field which I guess is empty? I will try to release a new version tomorrow.

**Comment by hansdez** [comment]
I've just typed in "@subject" in that field (and didn't actually use the replaceable subject in the filter url) and can confirm that I then no longer have the problem. I can use this for now until the new release comes out! 😍 Thanks!

**Comment by Maexotic** [comment]
Everything works like a charm. Thank you!
