### ISSUE TITLE
Some apps share more than URL

### ISSUE THREAD

**Issue by ghost** [daverix/urlforwarder#4]
Thank you for making this. I was looking for this a long time.

When shared using a webbrowser on Android only the URL is forwarded. That's what we want, so that the destination can decide what to do with it. E.g.: https://destination.tld/?url=http%3A%2F%2Fopensourceforu.com%2F2017%2F01%2Frenault-leverages-open-source-build-electric-car-projects%2F

But some apps (like Inoreader) share a string like this: "Title word1 word2 etc https://url.tld". This is unfortunately forwarded as an URL and the destination can't do anything with that. E.g.: https://destination.tld/?url=Renault+leverages+open+source+to+build+electric+car+projects+http%3A%2F%2Fopensourceforu.com%2F2017%2F01%2Frenault-leverages-open-source-build-electric-car-projects%2F

Is there a way to fix this? Do I need to put something in the 'Replaceable text' field and what exactly? Or is this something that needs to be fixed in the code?

**Comment by daverix** [comment]
Sorry, no it's currently not possible. I could look after words that start with "http:" or "https:", would that work?

**Comment by jeroenpraat** [comment]
Yes that will possibly work if the intended use case is always to forward a http(s)-URL.

**Comment by daverix** [comment]
You want a regex to work with otherwise?

**Comment by jeroenpraat** [comment]
For me personally to look for http(s) is enough, but I was more thinking for other people.
